// +build sample
// Code generated by example_generator_test.go DO NOT EDIT.

package example

import (
	appenv "github.com/kyoh86/appenv"
	"io"
)

func GetAccess(yamlReader io.Reader, keyringService string, envarPrefix string) (access Access, err error) {
	yml, err := loadYAML(yamlReader)
	if err != nil {
		return access, err
	}
	return buildAccess(yml, envarPrefix)
}

func buildAccess(yml YAML, keyringService string, envarPrefix string) (access Access, err error) {
	keyring, err := loadKeyring(keyringService)
	if err != nil {
		return access, err
	}
	envar, err := getEnvar(envarPrefix)
	if err != nil {
		return access, err
	}
	access.hostName = new(appenv.HostName).Default().(string)
	if yml.HostName != nil {
		access.hostName = yml.HostName.Value().(string)
	}
	if envar.HostName != nil {
		access.hostName = envar.HostName.Value().(string)
	}

	access.dryRun = new(appenv.DryRun).Default().(bool)
	if envar.DryRun != nil {
		access.dryRun = envar.DryRun.Value().(bool)
	}

	access.token = new(appenv.Token).Default().(string)
	if keyring.Token != nil {
		access.token = keyring.Token.Value().(string)
	}

	return
}

type Access struct {
	hostName string
	dryRun   bool
	token    string
}

func (a *Access) HostName() string {
	return a.hostName
}

func (a *Access) DryRun() bool {
	return a.dryRun
}

func (a *Access) Token() string {
	return a.token
}
