// +build sample
// Code generated by example_generator_test.go DO NOT EDIT.

package example

import "io"

func GetAppenv(yamlReader io.Reader, keyringService string, envarPrefix string) (config Config, access Access, err error) {
	yml, err := loadYAML(yamlReader)
	if err != nil {
		return config, access, err
	}
	config, err = buildConfig(yml, keyringService)
	if err != nil {
		return config, access, err
	}
	access, err = buildAccess(yml, envarPrefix)
	if err != nil {
		return config, access, err
	}
	return config, access, nil
}
