// +build sample
// Code generated by example_generator_test.go DO NOT EDIT.

package example

import (
	"fmt"
	appenv "github.com/kyoh86/appenv"
	types "github.com/kyoh86/appenv/types"
	"io"
)

type Config struct {
	yml     YAML
	keyring Keyring
}

func GetConfig(yamlReader io.Reader, keyringService string) (config Config, err error) {
	yml, err := loadYAML(yamlReader)
	if err != nil {
		return config, err
	}
	return buildConfig(yml, keyringService)
}

func buildConfig(yml YAML, keyringService string) (config Config, err error) {
	keyring, err := loadKeyring(keyringService)
	if err != nil {
		return config, err
	}
	config.yml = yml
	config.keyring = keyring
	return
}

func (c *Config) Save(yamlWriter io.Writer, keyringService string) error {
	if err := saveYAML(yamlWriter, &c.yml); err != nil {
		return err
	}
	if err := saveKeyring(keyringService, &c.keyring); err != nil {
		return err
	}
	return nil
}

func OptionNames() []string {
	return []string{"host.name", "dry.run", "token"}
}

func (a *Config) Option(name string) (types.Config, error) {
	switch name {
	case "host.name":
		return &hostNameConfig{parent: a}, nil
	case "dry.run":
		return &dryRunConfig{parent: a}, nil
	case "token":
		return &tokenConfig{parent: a}, nil
	}
	return nil, fmt.Errorf("invalid option name %q", name)
}

func (a *Config) HostName() types.Config {
	return &hostNameConfig{parent: a}
}

type hostNameConfig struct {
	parent *Config
}

func (a *hostNameConfig) Get() (string, error) {
	{
		p := a.parent.yml.HostName
		if p != nil {
			text, err := p.MarshalText()
			return string(text), err
		}
	}
	return "", nil
}

func (a *hostNameConfig) Set(value string) error {
	{
		p := a.parent.yml.HostName
		if p == nil {
			p = new(appenv.HostName)
		}
		if err := p.UnmarshalText([]byte(value)); err != nil {
			return err
		}
		a.parent.yml.HostName = p
	}
	return nil
}

func (a *hostNameConfig) Unset() {
	a.parent.yml.HostName = nil
}

func (a *Config) DryRun() types.Config {
	return &dryRunConfig{parent: a}
}

type dryRunConfig struct {
	parent *Config
}

func (a *dryRunConfig) Get() (string, error) {
	return "", nil
}

func (a *dryRunConfig) Set(value string) error {
	return nil
}

func (a *dryRunConfig) Unset() {}

func (a *Config) Token() types.Config {
	return &tokenConfig{parent: a}
}

type tokenConfig struct {
	parent *Config
}

func (a *tokenConfig) Get() (string, error) {
	{
		p := a.parent.keyring.Token
		if p != nil {
			text, err := p.MarshalText()
			return string(text), err
		}
	}
	return "", nil
}

func (a *tokenConfig) Set(value string) error {
	{
		p := a.parent.keyring.Token
		if p == nil {
			p = new(appenv.Token)
		}
		if err := p.UnmarshalText([]byte(value)); err != nil {
			return err
		}
		a.parent.keyring.Token = p
	}
	return nil
}

func (a *tokenConfig) Unset() {
	a.parent.keyring.Token = nil
}
