// +build sample
// Code generated by example_generator_test.go DO NOT EDIT.

package example

import (
	appenv "github.com/kyoh86/appenv"
	gostrcase "github.com/stoewer/go-strcase"
	"os"
)

type Envar struct {
	HostName *appenv.HostName
	DryRun   *appenv.DryRun
}

func getEnvar(prefix string) (envar Envar, err error) {
	prefix = gostrcase.UpperSnakeCase(prefix)
	{
		v := os.Getenv(prefix + "HOST_NAME")
		if v != "" {
			var value appenv.HostName
			if err = value.UnmarshalText([]byte(v)); err != nil {
				return envar, err
			}
			envar.HostName = &value
		}
	}
	{
		v := os.Getenv(prefix + "DRY_RUN")
		if v != "" {
			var value appenv.DryRun
			if err = value.UnmarshalText([]byte(v)); err != nil {
				return envar, err
			}
			envar.DryRun = &value
		}
	}
	return
}
