// +build sample
// Code generated by example_generator_test.go DO NOT EDIT.

package example

import (
	appenv "github.com/kyoh86/appenv"
	keyring "github.com/zalando/go-keyring"
)

const DiscardKeyringService string = ""

type Keyring struct {
	Token *appenv.Token
}

func loadKeyring(keyringService string) (key Keyring, err error) {
	if keyringService == DiscardKeyringService {
		return
	}
	{
		v, err := keyring.Get(keyringService, "token")
		if err == nil {
			var value appenv.Token
			if err = value.UnmarshalText([]byte(v)); err != nil {
				return key, err
			}
			key.Token = &value
		}
	}
	return
}

func saveKeyring(keyringService string, key *Keyring) (err error) {
	if keyringService == DiscardKeyringService {
		return
	}
	{
		buf, err := key.Token.MarshalText()
		if err != nil {
			return err
		}
		if err := keyring.Set(keyringService, "token", string(buf)); err != nil {
			return err
		}
	}
	return nil
}
